[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xtaskops = { git = "https://github.com/jondot/xtaskops.git", rev = "95153c3"}
anyhow = "1"
