// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function RescriptComponent(props) {
  return React.createElement("div", undefined, React.createElement("p", {
                  "data-testid": "text-content"
                }, "Rescript component"));
}

var make = RescriptComponent;

export {
  make ,
}
/* react Not a pure module */
